AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for CloudWatch Logs.

Resources:
FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-library-frontend-bucket-sheshan-hebron
      WebsiteConfiguration:
        IndexDocument: index.html

  # CloudWatch Log Group
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /bidding-app/logs
      RetentionInDays: 30

Outputs:
  CloudWatchLogGroup:
    Description: "CloudWatch Log Group Name"
    Value: !Ref CloudWatchLogGroup
