AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for CloudWatch Logs.

Resources:
  FrontendS3Bucket:
    Type: AWS::S3::Bucket

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        ImageId: ami-05edb7c94b324f73c  # Replace with a valid AMI ID for your region
        InstanceType: t3.micro          # Replace with your desired instance type
        SecurityGroupIds:
          - sg-002f5a2e1c10ce54a        # Replace with your Security Group ID
        KeyName: bidding                # Replace with your EC2 key pair name
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo "Hello, World!" > /tmp/hello.txt

  # Auto Scaling Group
  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
      VPCZoneIdentifier:
        - subnet-092d0d335b3d7ad0a  # Replace with your Subnet ID
        - subnet-03c1c466698b3a209  # Replace with another Subnet ID
      TargetGroupARNs:
        - !Ref MyTargetGroup

  
  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: KinesisAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:ListStreams
                Resource: !GetAtt MyKinesisStream.Arn
        - PolicyName: CloudWatchLogsAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # Kinesis Event Source Mapping for Lambda
  MyKinesisEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MyKinesisStream.Arn
      FunctionName: !GetAtt MyLambdaFunction.Arn
      StartingPosition: LATEST



   # Load Balancer
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - subnet-092d0d335b3d7ad0a  # Replace with your Subnet ID
        - subnet-03c1c466698b3a209  # Replace with another Subnet ID
      SecurityGroups:
        - sg-002f5a2e1c10ce54a      # Replace with your Security Group ID
      Scheme: internet-facing       # Use 'internal' for an internal load balancer
      Type: application             # Use 'network' for a Network Load Balancer

  # Target Group
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: vpc-0b92707bcabd82204 # Replace with your VPC ID
      HealthCheckPath: /            # Health check path
      HealthCheckPort: 80           # Health check port
      HealthCheckProtocol: HTTP     # Health check protocol


   # Kinesis Data Stream for Real-Time Analytics
  MyKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: MyKinesisStream
      ShardCount: 1

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3

          def handler(event, context):
              for record in event['Records']:
                  payload = json.loads(record['kinesis']['data'])
                  print("Processed record:", payload)
      Runtime: python3.9
      Timeout: 10
      
      
  # CloudWatch Log Group
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /the_app/logs
      RetentionInDays: 30
Outputs:
  CloudWatchLogGroup:
    Description: "CloudWatch Log Group Name"
    Value: !Ref CloudWatchLogGroup
#dynamodb comment
  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref DynamoDBTable


